export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SET_MODAL_TITLE = "SET_MODAL_TITLE";

export const SET_SELECTED_ADMINS_CHANGE = "SET_SELECTED_ADMINS_CHANGE";

export const ADD_ITEMS_TO_TABLE = "ADD_ITEMS_TO_TABLE";
export const REMOVE_ITEMS_FROM_TABLE = "REMOVE_ITEMS_FROM_TABLE";
export const SET_TABLE_CURRENT_DATA = "SET_TABLE_CURRENT_DATA";
export const EDIT_TABLE_CURRENT_DATA = "EDIT_TABLE_CURRENT_DATA";

export const SET_TABLE_DATA = "SET_TABLE_DATA"
export const EDIT_TABLE_DATA = "EDIT_TABLE_DATA";

export const SET_TABLE_TYPE = "SET_TABLE_TYPE";
